DC-7463-magic-search-broken
downhome/EasyAutocomplete pull request #1
Opened 2021-05-24 13:26 UTC by MaiAbuthraa

2021-05-24 17:58 UTC, gmhawash requested changes

2021-05-24 17:58 UTC, gmhawash commented on dist/jquery.easy-autocomplete.js
> -		};
instead of removing it, check if `config. categories` exist, use it; otherwise, build it dynamically.

2021-05-25 11:41 UTC, MaiAbuthraa commented on src/list.builder.js
> +        if (configuration.getOptions('categories') !== undefined) {
Using configuration.get("categories") that will give you the default value if we do not set categories 
![Screen Shot 2021-05-25 at 2 16 51 PM](https://user-images.githubusercontent.com/2033729/119491988-40b7ca80-bd67-11eb-8246-601b809e8385.png)
that why add a new function the return the options that sent to check if the categories or not.

2021-05-25 13:48 UTC, gmhawash approved these changes

2021-05-25 16:43 UTC, merged